server:
  port: 8081
  servlet: 
    context-path: /nfdw-admin
spring:
  devtools:
    restart:
      enabled: true
  datasource:
    druid:
      type: com.alibaba.druid.pool.DruidDataSource
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: \*\.js, \*\.gif, \*\.jpg, \*\.png, \*\.css,  \*\.ico, /druid/\*
        session-stat-enable: true
        session-stat-max-count: 1000
        principal-session-name: curentUser.username
        profile-enable: true
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
      aop-patterns: com.nfdw.service.impl.*
      
    primary: 
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://172.16.91.215:3306/shenzhennew?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      username: root
      password: nfdw123456
      
    secondary: 
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://172.16.91.215:3306/shenzhennew?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      username: root
      password: nfdw123456

  redis: 
    password: gpdi123456.
    jedis: 
      pool: 
        max-total: 1024
        max-wait: 15000
        max-idle: 200
        min-idle: 10
        testWhileIdle: true
        timeBetweenEvictionRunsMillis: 30000
    sentinel: 
      master: mymaster
      nodes: 172.16.91.219:26379,172.16.91.217:26379

  http:
    encoding:
      force: true
  boot:
    admin:
      client:
        prefer-ip: true
      url: http://localhost:8082
  freemarker: 
    allow-session-override: true
  servlet:
    multipart:
      max-file-size: 100MB

mybatis:
  type-aliases-package: com.nfdw.entity
  mapper-locations: classpath*:mapper/*.xml
  check-config-location: true
  configuration: 
    cache-enabled: false 
    aggressive-lazy-loading: false 
    multiple-result-sets-enabled: true 
    map-underscore-to-camel-case: true 
    use-generated-keys: true 
    default-executor-type: BATCH 
    default-statement-timeout: 600 
    log-impl: org.apache.ibatis.logging.log4j.Log4jImpl
mapper:
  mappers:
    - com.nfdw.base.BaseMapper
    - tk.mybatis.mapper.common.Mapper
  not-empty: true
  identity: mysql


# PageHelperConfig 可以替代此方案
pagehelper:
  helperDialect: mysql
  offsetAsPageNum: true 
  rowBoundsWithCount: true
  pageSizeZero: true 
  reasonable: false 
  supportMethodsArguments: true
  params: count=countSql

lenosp:
  uploadPath: ./file/
  isDayType: false

  imagePath: ./image/

logging:
  file: ./logs/nfdw-log.log
  level:
    com.nfdw.mapper: debug

dataType: mysql

multipart:
  enabled: true
